%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-eigenpy
Version:        1.6.7
Release:        2%{?dist}
Summary:        ROS eigenpy package

License:        BSD
URL:            https://github.com/stack-of-tasks/eigenpy
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python2-devel
Requires:       boost-python3-devel
Requires:       eigen3-devel
Requires:       numpy
Requires:       python-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python2-devel
BuildRequires:  boost-python3-devel
BuildRequires:  cmake
BuildRequires:  doxygen
BuildRequires:  eigen3-devel
BuildRequires:  git
BuildRequires:  numpy
BuildRequires:  python-devel

%description
Bindings between Numpy and Eigen using Boost.Python

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Mon Nov 25 2019 Justin Carpentier <justin.carpentier@inria.fr> - 1.6.7-2
- Autogenerated by Bloom

* Fri Nov 15 2019 Justin Carpentier <justin.carpentier@inria.fr> - 1.6.7-1
- Autogenerated by Bloom

* Sat Nov 09 2019 Justin Carpentier <justin.carpentier@inria.fr> - 1.6.5-1
- Autogenerated by Bloom

* Thu Oct 24 2019 Justin Carpentier <justin.carpentier@inria.fr> - 1.6.2-1
- Autogenerated by Bloom

* Tue Apr 30 2019 Wolfgang Merkt <wolfgang.merkt@ed.ac.uk> - 1.5.1-2
- Autogenerated by Bloom

* Tue Apr 30 2019 Wolfgang Merkt <wolfgang.merkt@ed.ac.uk> - 1.5.1-1
- Autogenerated by Bloom

* Wed Jan 30 2019 Wolfgang Merkt <wolfgang.merkt@ed.ac.uk> - 1.5.0-1
- Autogenerated by Bloom

* Wed Jan 30 2019 Wolfgang Merkt <wolfgang.merkt@ed.ac.uk> - 1.5.0-0
- Autogenerated by Bloom

